# Generated by Django 2.2.2 on 2019-06-12 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('luogo_nascita', models.CharField(max_length=100)),
                ('cf', models.CharField(blank=True, max_length=16, null=True)),
                ('domicilio', models.CharField(max_length=300)),
                ('provincia', models.CharField(choices=[('Torino', 'TO'), ('Vercelli', 'VC'), ('Novara', 'NO'), ('Cuneo', 'CN'), ('Asti', 'AT'), ('Alessandria', 'AL'), ('Biella', 'BI'), ('Verbano-Cusio-Ossola', 'VB'), ('Aosta', 'AO'), ('Varese', 'VA'), ('Como', 'CO'), ('Sondrio', 'SO'), ('Milano', 'MI'), ('Bergamo', 'BG'), ('Brescia', 'BS'), ('Pavia', 'PV'), ('Cremona', 'CR'), ('Mantova', 'MN'), ('Lecco', 'LC'), ('Lodi', 'LO'), ('Monza e della Brianza', 'MB'), ('Bolzano/Bozen', 'BZ'), ('Trento', 'TN'), ('Verona', 'VR'), ('Vicenza', 'VI'), ('Belluno', 'BL'), ('Treviso', 'TV'), ('Venezia', 'VE'), ('Padova', 'PD'), ('Rovigo', 'RO'), ('Udine', 'UD'), ('Gorizia', 'GO'), ('Trieste', 'TS'), ('Pordenone', 'PN'), ('Imperia', 'IM'), ('Savona', 'SV'), ('Genova', 'GE'), ('La Spezia', 'SP'), ('Piacenza', 'PC'), ('Parma', 'PR'), ("Reggio nell'Emilia", 'RE'), ('Modena', 'MO'), ('Bologna', 'BO'), ('Ferrara', 'FE'), ('Ravenna', 'RA'), ('Forli-Cesena', 'FC'), ('Rimini', 'RN'), ('Massa-Carrara', 'MS'), ('Lucca', 'LU'), ('Pistoia', 'PT'), ('Firenze', 'FI'), ('Livorno', 'LI'), ('Pisa', 'PI'), ('Arezzo', 'AR'), ('Siena', 'SI'), ('Grosseto', 'GR'), ('Prato', 'PO'), ('Perugia', 'PG'), ('Terni', 'TR'), ('Pesaro e Urbino', 'PU'), ('Ancona', 'AN'), ('Macerata', 'MC'), ('Ascoli Piceno', 'AP'), ('Fermo', 'FM'), ('Viterbo', 'VT'), ('Rieti', 'RI'), ('Roma', 'RM'), ('Latina', 'LT'), ('Frosinone', 'FR'), ("L'Aquila", 'AQ'), ('Teramo', 'TE'), ('Pescara', 'PE'), ('Chieti', 'CH'), ('Campobasso', 'CB'), ('Isernia', 'IS'), ('Caserta', 'CE'), ('Benevento', 'BN'), ('Napoli', 'NA'), ('Avellino', 'AV'), ('Salerno', 'SA'), ('Foggia', 'FG'), ('Bari', 'BA'), ('Taranto', 'TA'), ('Brindisi', 'BR'), ('Lecce', 'LE'), ('Barletta-Andria-Trani', 'BT'), ('Potenza', 'PZ'), ('Matera', 'MT'), ('Cosenza', 'CS'), ('Catanzaro', 'CZ'), ('Reggio di Calabria', 'RC'), ('Crotone', 'KR'), ('Vibo Valentia', 'VV'), ('Trapani', 'TP'), ('Palermo', 'PA'), ('Messina', 'ME'), ('Agrigento', 'AG'), ('Caltanissetta', 'CL'), ('Enna', 'EN'), ('Catania', 'CT'), ('Ragusa', 'RG'), ('Siracusa', 'SR'), ('Sassari', 'SS'), ('Nuoro', 'NU'), ('Cagliari', 'CA'), ('Oristano', 'OR'), ('Olbia-Tempio', 'OT'), ('Ogliastra', 'OG'), ('Medio Campidano', 'VS'), ('Carbonia-Iglesias', 'CI')], max_length=2)),
                ('qualifica', models.CharField(choices=[('DOTTORANDO', 'Dottorando'), ('ASSEGNISTA', 'Assegnista'), ('STUDENTE', 'Studente'), ('DOCENTE', 'Docente')], max_length=10)),
                ('struttura_fondi', models.CharField(max_length=200)),
                ('datore_lavoro', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
