# Generated by Django 2.2.2 on 2019-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0002_edit_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cf',
        ),
        migrations.AddField(
            model_name='profile',
            name='sesso',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, null=True),
        ),
    ]
