# Generated by Django 2.2.2 on 2019-06-12 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RimborsiApp', '0004_edit_profile_luogo_nascita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='domicilio',
            new_name='domicilio_fiscale',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='provincia',
            new_name='domicilio_fiscale_provincia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='struttura_fondi',
        ),
        migrations.CreateModel(
            name='Missione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinazione', models.CharField(max_length=100)),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('fondo', models.CharField(max_length=100)),
                ('mezzo', models.CharField(max_length=100)),
                ('motivazione', models.CharField(blank=True, max_length=100, null=True)),
                ('targa', models.CharField(blank=True, max_length=7, null=True)),
                ('struttura_fondi', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
