# Generated by Django 2.2.2 on 2019-06-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0006_edit_comuni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='luogo_nascita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RimborsiApp.Comune'),
        ),
    ]
