# Generated by Django 2.2.2 on 2019-06-19 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RimborsiApp', '0007_edit_comuni_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='luogo_nascita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RimborsiApp.Comune'),
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=100)),
                ('targa', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
