# Generated by Django 2.2.2 on 2019-06-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0010_add_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
                ('massimale_docenti', models.FloatField()),
                ('massimale_tecnici', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.AddField(
            model_name='stato',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RimborsiApp.Categoria'),
        ),
    ]
