# Generated by Django 2.2.2 on 2019-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0012_add_scontrino'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='fine_ora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='inizio_ora',
            field=models.TimeField(null=True),
        ),
    ]
