# Generated by Django 2.2.2 on 2019-06-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0013_add_ore_missione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='fine_ora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='missione',
            name='inizio_ora',
            field=models.TimeField(default='19:20:00'),
            preserve_default=False,
        ),
    ]
