# Generated by Django 2.2.2 on 2019-06-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0014_edit_ore_missione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missione',
            name='mezzo',
        ),
        migrations.AddField(
            model_name='missione',
            name='pernottamento',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='scontrino',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='Trasporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('da', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
                ('mezzo', models.CharField(choices=[('AUTO', 'Auto'), ('AEREO', 'Aereo'), ('TRENO', 'Treno'), ('BUS', 'Bus')], max_length=5)),
                ('tipo_costo', models.CharField(max_length=50)),
                ('costo', models.FloatField()),
                ('missione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RimborsiApp.Missione')),
            ],
            options={
                'verbose_name_plural': 'Trasporti',
            },
        ),
    ]
