# Generated by Django 2.2.2 on 2019-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0015_add_trasporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='altrespese',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='fine',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='missione',
            name='inizio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='missione',
            name='pernottamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='scontrino',
            field=models.TextField(blank=True, null=True),
        ),
    ]
