# Generated by Django 2.2.2 on 2019-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0016_edit_inizio_fine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='convegno',
            field=models.TextField(blank=True, null=True),
        ),
    ]
