# Generated by Django 2.2.2 on 2019-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0017_add_convegno'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasporto',
            name='km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
