# Generated by Django 2.2.2 on 2019-06-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0018_add_km_in_trasporto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRichiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_1', models.DateField()),
                ('parte_2', models.DateField()),
                ('kasko', models.DateField()),
                ('dottorandi', models.DateField()),
                ('missione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RimborsiApp.Missione')),
            ],
            options={
                'verbose_name': 'Data di Richiesta',
                'verbose_name_plural': 'Date di Richiesta',
            },
        ),
    ]
