# Generated by Django 2.2.2 on 2019-06-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0019_add_date_richiesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuliMissione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_1', models.DateField()),
                ('parte_2', models.DateField()),
                ('kasko', models.DateField()),
                ('dottorandi', models.DateField()),
                ('missione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RimborsiApp.Missione')),
            ],
            options={
                'verbose_name': 'Moduli missione',
                'verbose_name_plural': 'Moduli missioni',
            },
        ),
        migrations.DeleteModel(
            name='DateRichiesta',
        ),
    ]
