# Generated by Django 2.2.2 on 2019-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0020_edit_date_richiesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulimissione',
            name='dottorandi_file',
            field=models.FileField(blank=True, null=True, upload_to='moduli/'),
        ),
        migrations.AddField(
            model_name='modulimissione',
            name='kasko_file',
            field=models.FileField(blank=True, null=True, upload_to='moduli/'),
        ),
        migrations.AddField(
            model_name='modulimissione',
            name='parte_1_file',
            field=models.FileField(blank=True, null=True, upload_to='moduli/'),
        ),
        migrations.AddField(
            model_name='modulimissione',
            name='parte_2_file',
            field=models.FileField(blank=True, null=True, upload_to='moduli/'),
        ),
    ]
