# Generated by Django 2.2.2 on 2019-07-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0021_edit_moduli_missione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
    ]
