# Generated by Django 2.2.3 on 2019-07-12 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0024_add_motivazione_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulimissione',
            name='atto_notorio',
            field=models.DateField(default=datetime.date(2019, 7, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulimissione',
            name='atto_notorio_file',
            field=models.FileField(blank=True, null=True, upload_to='moduli/'),
        ),
    ]
