# Generated by Django 2.2.3 on 2019-07-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0028_add_luogonascita2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='luogo_nascita_2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='luogo_nascita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.Comune'),
        ),
    ]
