# Generated by Django 2.2.3 on 2019-07-29 17:26

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0031_add_atto_notorio_dichiarazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulimissione',
            name='atto_notorio_file',
            field=models.FileField(blank=True, null=True, storage=RimborsiApp.storage.OverwriteStorage(), upload_to='moduli/'),
        ),
        migrations.AlterField(
            model_name='modulimissione',
            name='dottorandi_file',
            field=models.FileField(blank=True, null=True, storage=RimborsiApp.storage.OverwriteStorage(), upload_to='moduli/'),
        ),
        migrations.AlterField(
            model_name='modulimissione',
            name='kasko_file',
            field=models.FileField(blank=True, null=True, storage=RimborsiApp.storage.OverwriteStorage(), upload_to='moduli/'),
        ),
        migrations.AlterField(
            model_name='modulimissione',
            name='parte_1_file',
            field=models.FileField(blank=True, null=True, storage=RimborsiApp.storage.OverwriteStorage(), upload_to='moduli/'),
        ),
        migrations.AlterField(
            model_name='modulimissione',
            name='parte_2_file',
            field=models.FileField(blank=True, null=True, storage=RimborsiApp.storage.OverwriteStorage(), upload_to='moduli/'),
        ),
    ]
