# Generated by Django 2.2.3 on 2019-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0032_edit_filefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasporto',
            name='a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trasporto',
            name='da',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trasporto',
            name='mezzo',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('AEREO', 'Aereo'), ('TRENO', 'Treno'), ('BUS', 'Bus'), ('TAXI', 'Taxi')], max_length=5),
        ),
        migrations.AlterField(
            model_name='trasporto',
            name='tipo_costo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
