# Generated by Django 2.2.3 on 2019-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0033_edit_trasporto_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='automobile_altrui',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualifica',
            field=models.CharField(choices=[('DOTTORANDO', 'Dottorando'), ('ASSEGNISTA', 'Assegnista'), ('STUDENTE', 'Studente'), ('PO', 'Professore Ordinario'), ('PA', 'Professore Associato'), ('RU', 'Ricercatore Universitario'), ('RTDA', 'Ricercatore a tempo determinato A'), ('RTDB', 'Ricercatore a tempo determinato B')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trasporto',
            name='mezzo',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('AUTO_altrui', 'Auto altrui'), ('AEREO', 'Aereo'), ('TRENO', 'Treno'), ('BUS', 'Bus'), ('TAXI', 'Taxi')], max_length=5),
        ),
    ]
