# Generated by Django 2.2.3 on 2019-07-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0034_add_automobile_altrui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulimissione',
            name='dottorandi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasporto',
            name='mezzo',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('A_ALT', 'Auto altrui'), ('AEREO', 'Aereo'), ('TRENO', 'Treno'), ('BUS', 'Bus'), ('TAXI', 'Taxi')], max_length=5),
        ),
    ]
