# Generated by Django 2.2.3 on 2019-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0035_edit_missioneform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='motivazione',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
