# Generated by Django 2.2.3 on 2019-09-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0036_edit_missione_motivazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='tipo',
            field=models.CharField(choices=[('RICERCA', 'Missione di Ricerca/Didattica'), ('PROGETTO', 'Missione di Progetto')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualifica',
            field=models.CharField(choices=[('DOTTORANDO', 'Dottorando'), ('ASSEGNISTA', 'Assegnista'), ('STUDENTE', 'Studente'), ('PO', 'Professore Ordinario'), ('PA', 'Professore Associato'), ('RU', 'Ric. Universitario'), ('RTDA', 'RTDA'), ('RTDB', 'RTDB')], max_length=10, null=True),
        ),
    ]
