# Generated by Django 2.2.3 on 2019-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0038_edit_trasporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='missione_conclusa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
