# Generated by Django 2.2.3 on 2020-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0039_edit_missione'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_fine_rapporto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
