# Generated by Django 2.2.3 on 2020-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0043_add_straniero_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='luogo_nascita_straniero',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
