# Generated by Django 2.2.3 on 2020-01-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0044_add_luogo_nascita_straniero_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domicilio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilio', to='RimborsiApp.Indirizzo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='luogo_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.Comune'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='luogo_nascita_straniero',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='residenza',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residenza', to='RimborsiApp.Indirizzo'),
        ),
    ]
